title: Project

tabs:
  main:
    label: Project Details
    icon: globe

    columns:
      left:
        width: 2/3
        sections:
        fields:
          content:
            label: Content
            type: layout
          
      right:
        width: 1/3
        sections:
        fields:
          cover:
            label: Cover
            type: files
            layout: cards
            multiple: false
            size: full
            text: " "
          projectIntro:
            label: Project Intro
            type: textarea
            size: small
            help: "A short introduction to the project that lives on the homepage card"
          backgroundColor:
            label: Background Colour
            type: color
            width: 1/2
          textColor:
            label: Text Colour
            type: color
            width: 1/2
            options:
              "Light": "#ECE2CD"
              "Dark": "#181716"
          projectTagline:
            label: Project Tagline
            type: text
          projectCategory:
            label: Category
            type: select
            width: 1/2
            options:
              "keycap": Keycap Set
              "keyboard": Keyboard
              "switch": Switch
              "deskmat": Deskmat
          projectStatus:
            label: Status
            type: text
            width: 1/2
          projectFacts:
            label: Key Facts
            type: structure
            fields:
              fact:
                label: Fact
                type: text
            help: Key details that will go in the marquee
          assets:
            label: Assets
            type: files
            multiple: true
            size: full
            query: page.images
            image:
              cover: true
          

          
          
  seo: seo/site

          