title: Site

tabs:
  main:
    label: Main
    icon: globe

    columns:
      left:
        width: 2/3
        sections:
          pages:
            label: Projects
            type: pages
            limit: 999
            layout: cards
            image:
              cover: true
            templates:
              - project
              - home
              query: "{{ page.cover.toFile }}"
              color: white
            info: "{{ page.category }}"
      right:
        width: 1/3
        sections:
        fields:
          logo:
            label: Logo
            type: files
            layout: cards
            cover: true
            multiple: false
            size: small
            text: " "
          socials:
            label: Social Links
            type: structure
            fields:
              title:
                label: Title
                type: text
              url:
                label: URL
                type: url
              icon:
                label: Icon
                type: files
                layout: cards
                limit: 1
          
          newsletter:
            label: Newsletter Link
            type: url
          
  seo: seo/site

          