title: Site

tabs:
  main:
    label: Main
    icon: globe

    columns:
      left:
        width: 1/2
        sections:
          projects:
            label: Projects
            type: pages
            limit: 999
            layout: cardlets
            image:
              cover: true
              query: page.cover.toFile
              color: white
            templates:
              - project
            info: "{{ page.category }}"
      right:
        width: 1/2
        sections:
          pages:
            type: pages
            templates:
              - newsletters
              - home
              - error
              - default
          fields:
            type: fields
            fields:
              logo:
                label: Logo
                type: files
                layout: list
                cover: true
                multiple: false
                size: small
                text: " "
              newsletter:
                label: Newsletter Link
                type: url
              socials:
                label: Social Links
                type: structure
                fields:
                  title:
                    label: Title
                    type: text
                  url:
                    label: URL
                    type: url
                  icon:
                    label: Icon
                    type: files
                    layout: cards
                    limit: 1

  seo: seo/site

